const month= "jan"
switch (month){
    case"jan":
    console.log("January")
    break;
    case"feb":
    console.log("February")
    break;
    case"mar":
    console.log("March")
    break;
    case"apr":
    console.log("April")
    break;
    case"may":
    console.log("May")
    break;
    case"jun":
    console.log("June")
    break;
    case"jul":
    console.log("July")
    break;
    case"aug":
    console.log("August")
    break;
    case"sep":
    console.log("September")
    break;
    case"oct":
    console.log("October")
    break;
    case"nov":
    console.log("November")
    break;
    case"dec":
    console.log("December")
    break;
    default:
        console.log("default case match");
        break;
}
